### ISSUE TITLE
Beware of the universal selector

### ISSUE THREAD

**Issue by zachfedor** [briangx92/more-css-practice#6]
https://github.com/briangx92/more-css-practice/blob/687c39c9ab49e7cb35a71243ae70d686f9343ccd/github/styles.css#L1-L2

The universal selector shouldn't be overused. It's not performant, and it's got the potential to remove helpful defaults and conventions.

**Comment by briangx92** [comment]
I know every code can be written in many ways but what would you typically see a time to use it.
