### ISSUE TITLE
Margin shorthand used in margin-top

### ISSUE THREAD

**Issue by zachfedor** [briangx92/more-css-practice#7]
https://github.com/briangx92/more-css-practice/blob/687c39c9ab49e7cb35a71243ae70d686f9343ccd/amazon/styles.css#L4

You're trying to use a shorthand value for `margin` on the `margin-top` property, which won't work. Pick one or the other.

**Comment by briangx92** [comment]
It would've been different if I had used margin and have those same values, right?
